### PR TITLE
[tests] Added unit tests for all of our validators. Fixed an issue with ...

### PR DESCRIPTION
**Pull request by jbest84**
...the isDateInRange validator, where it would not accept both minValue and maxValue.

@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by CHenrie** [comment]
@jbest84  Accepted

**Comment by slxbuilder** [comment]
Merged build finished.

**Pull request merged**
