### PR TITLE
[13091773] Turned on stemming, thesaurus, and phonic options for speedse...

### PR DESCRIPTION
**Pull request by jbest84**
...arch. This makes the search more natural. Documentation for these options is located on our dev wiki (we should probably include this in the help or on github wiki):

http://slxdevwiki.testlogix.com/Projects/Sawgrass/SpeedSearch

@CHenrie Please review.

### CODE REVIEW

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
retest this please

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by jbest84** [comment]
@CHenrie Please review again. I added an additional change from PM to set the thesaurus option to false. I also moved the options to Application so they can be app configurations later on if we want them to be.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
retest this please

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Pull request merged**
