### PR TITLE
Update readme.

### PR DESCRIPTION
**Pull request by jbest84**
Updated some links. Mostly doing a pull request to test the updated jenkins pull request builder plugin.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Build triggered.

**Comment by slxbuilder** [comment]
Build started.

**Comment by slxbuilder** [comment]
Build finished.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
retest this please

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
retest this please

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
retest this please

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
retest this please

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build finished.

**Pull request merged**
