### PR TITLE
[13091784] Fixed getFieldValues so it will initialize fields to an empty...

### PR DESCRIPTION
**Pull request by jbest84**
... string. Fixed JSHint warnings as well.

@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84  For searching string for lead is $account correct? 

```
             break;
```
-                case 'Lead': descriptor = string.substitute('${0} ${1} (${2})', this.getFieldValues(item.fields, ['firstname', 'lastname', 'account']));
-                case 'Lead': descriptor = string.substitute('${firstname} ${lastname} (${account})', this.getFieldValues(item.fields, ['firstname', 'lastname', 'account']));

**Comment by CHenrie** [comment]
@jbest84  Accpeted

**Comment by jbest84** [comment]
Validated by QA. Merging.

**Pull request merged**
