### PR TITLE
[13091819] When attempting to complete an occurance from the activity de...

### PR DESCRIPTION
**Pull request by jbest84**
...tail view, check to ensure the key is composite, if it is not, fetch the occurance before moving on to the complete view.

@CHenrie Please review

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by jbest84** [comment]
retest this please

**Comment by jbest84** [comment]
@CHenrie Please review updated commit

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by jbest84** [comment]
Validated by QA. Merging.

**Pull request merged**
