### PR TITLE
[13091670] Changed label for discount in opportunity product edit/insert...

### PR DESCRIPTION
**Pull request by jbest84**
@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by jbest84** [comment]
Validated by QA in DTS. Merging.

**Pull request merged**
