### PR TITLE
[13091666] Call disable() on the exchange rate date field instead of set...

### PR DESCRIPTION
**Pull request by jbest84**
...ting the disabled flag which is not working 100% in the SDK.

@CHenrie Please review. It looks like we need to fix the "disabled" flag in the SDK to set the input node to disabled as well. The disable function does this, so instead of setting the attribute, the work around is to call disable() on that field.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by jbest84** [comment]
Validated as fixed by QA. Merging.

**Pull request merged**
