### PR TITLE
[13091679] Conditionally load the multicurrency section for opportunity ...

### PR DESCRIPTION
**Pull request by jbest84**
...edit.

@CHenrie Needs review

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by jbest84** [comment]
retest this please

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Validated as fixed by QA in DTS. Merging.

**Pull request merged**
