### PR TITLE
[13091725] Clear multicurrency adjusted prices on program selection.

### PR DESCRIPTION
**Pull request by jbest84**
@CHenrie Please review.

### CODE REVIEW

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Validated by QA as fixed. Merging.

**Pull request merged**
