### PR TITLE
[13091813] Fix issue where completed user is null in notes history detail

### PR DESCRIPTION
**Pull request by jbest84**
@CHenrie Please review

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by gitCHenrie** [comment]
@jbest84 Accepted

**Comment by jbest84** [comment]
Validated by QA. Merging.

**Pull request merged**
