### PR TITLE
[13092216] Remove speedsearch from the top as a search input. Added new ...

### PR DESCRIPTION
**Pull request by jbest84**
...speedsearch item to the global menu.

@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84  I Accept

**Comment by jbest84** [comment]
Validated by QA - Merging

**Pull request merged**
