### PR TITLE
[12090969] Ability to remove/delete a product from the opportunity produ...

### PR DESCRIPTION
**Pull request by jbest84**
...cts list.

@CHenrie Needs Review.

This change will add a delete icon to the opportunity products detail screen so you can remove that product from the list.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84  Accepted

**Pull request merged**
