### PR TITLE
[13091717] Refresh my activites list when completing the activity throug...

### PR DESCRIPTION
**Pull request by jbest84**
...h the detail view.

@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84  Accepted

**Comment by jbest84** [comment]
Validated by QA as fixed. Merged.

**Pull request merged**
