### PR TITLE
[13091669] All extended price fields are set when the product is selecte...

### PR DESCRIPTION
**Pull request by jbest84**
...d, rather than just the first extended price. This is for multicurrency.

@CHenrie Please review.

### CODE REVIEW

**Comment by CHenrie** [comment]
Accepted

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
retest this please.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Validated as fixed by QA. Merging.

**Pull request merged**
