### PR TITLE
[13091772] Re-ordered default home view order. My activities, calendar, ...

### PR DESCRIPTION
**Pull request by jbest84**
...and notes history will now come first.

@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by jbest84** [comment]
Validated by QA. Merging.

**Pull request merged**
