### PR TITLE
Defect-13092146 Adding method to get the real activity Id for recurring activities

### PR DESCRIPTION
**Pull request by CHenrie**
Adding Defects 
13092146 [fixed]
13092154 [fixed]
13092153 [fixed]

### CODE REVIEW

**Comment by CHenrie** [comment]
@jbest84  Please review

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
@CHenrie Accept

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Please Review Again I added to more defects that was  in the same area an line in the AttachmentManager.js

**Comment by jbest84** [comment]
@CHenrie Accept

**Comment by jbest84** [comment]
Validated as fixed by QA. Merging.

**Pull request merged**
