### PR TITLE
[13091671] Use built in Number.toFixed instead of the SDK fixed formatter.

### PR DESCRIPTION
**Pull request by jbest84**
@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
Accepted

**Comment by jbest84** [comment]
Validated by QA as fixed. Merging.

**Pull request merged**
