### PR TITLE
Reverting back to js to prepare for ES6 instead of TypeScript.

### PR DESCRIPTION
**Pull request by jbest84**
Backing out of Typescript for now, due to https://github.com/Microsoft/TypeScript/issues/2719

### CODE REVIEW

**Comment by RyanFarley** [comment]
:+1:  x :100:

**Comment by jbest84** [comment]
@RyanFarley Not a TS fan?

**Comment by RyanFarley** [comment]
lol no :)

**Comment by jbest84** [comment]
Due to the issue above, and the fact that TypeScript does not support stamping in an AMD module ID, we are backing off (I had a branch dedicated to TypeScript modules, it was not yet merged). Are you just against TypeScript, or transpiling in general? We are considering pulling in my topic-babel branch and going ES6 to stay with the standard.

**Comment by jbest84** [comment]
@CHenrie [argos-sdk](https://github.com/Saleslogix/argos-sdk/pull/101) and argos-saleslogix have both been reverted from TS and types stripped away.

**Comment by RyanFarley** [comment]
Not exactly against transpiling, just never been a fan of typescript, but that's mainly because it feels less javascripty and I like javascript to feel javascripty - but to be honest I suppose I've never really given it a fair try. I'd be all for going es6 with babel.

**Comment by jbest84** [comment]
Typescript is nice, there is no doubt about that. Hopefully the TC39 committee will get something going in this area (Brendan Eich appears to be a fan of TS). After ES6 (Ecmascript 2015) they plan on doing a yearly summer release, or that was the plan. So hopefully we see ES7/ES8 soon! We just need Apple to get on board and start doing rolling releases for Safari.

**Comment by rjledger** [comment]
Jumping in here too.. Glad to see you dropped the typescript path - not a fan either. Agree w/Ryan's comments \* 1000% ;-)

**Pull request merged**
