### PR TITLE
Adding Error Handeling and maxfile configuration

### PR DESCRIPTION
**Pull request by CHenrie**
@jbest84 Please Review

### CODE REVIEW

**Comment by jbest84** [comment]
@CHenrie Accept

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build finished.

**Pull request merged**
