### PR TITLE
defect - 13091224 Added apply context to AddAccountContact View for defa...

### PR DESCRIPTION
**Pull request by CHenrie**
@jbest84 Please Review

### CODE REVIEW

**Comment by jbest84** [comment]
@CHenrie Accepted

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Flagged as fixed/validated in DTS. Merging.

**Pull request merged**
