### PR TITLE
[13091724][13091723] Added helper method to reload activity lists when n...

### PR DESCRIPTION
**Pull request by jbest84**
...ew activities are added, completed, or modified.

@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted:  To Do we need to investigate a more general pub and subscribe  service for all modules that have lists that need refreshing.

**Comment by jbest84** [comment]
Validated as fixed by QA. Merging.

**Pull request merged**
