### PR TITLE
Defect 13091665 Adding ExchangeRate Validator and defeualt setting the c...

### PR DESCRIPTION
**Pull request by CHenrie**
@jbest84 Please Review
...ode, rate and date from $template when adding opportunity. Also changed exchange rate date to format as date time.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by jbest84** [comment]
@CHenrie Accept.

**Comment by slxbuilder** [comment]
Merged build finished.

**Pull request merged**
