### PR TITLE
[13092262] Fix "no records" card for week view to have a white backgroun...

### PR DESCRIPTION
**Pull request by jbest84**
...d and border radius.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Validated by QA as fixed. Merging.

**Pull request merged**
