### PR TITLE
[13091775, 13091804] Adding enbaleUI function to toggle fields when there is not a product or...

### PR DESCRIPTION
**Pull request by CHenrie**
@jbest84 Please Review

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by jbest84** [comment]
@CHenrie Accept

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Validated by QA. Merging.

**Pull request merged**
