### PR TITLE
Show "All day" instead of a relative date for timeless activities.

### PR DESCRIPTION
**Pull request by jbest84**
# MBL-10402

@CHenrie Please review

### CODE REVIEW

**Comment by CHenrie** [comment]
@jbest84 Accpeted

**Comment by rjledger** [comment]
Timeless is not and never has been an “all Day” thing. It’s just an activity that could be done at any time.

Why change what is not broken?
rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
We could change "all day" to timeless perhaps. Having a relative time didn't make sense.

**Comment by rjledger** [comment]
“timeless” really makes a lot of sense.

A typical way people use “timeless” is to create them w/rollover. It’s like that list of things/activities you have in your notebook you work on when you have “time” ;-)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Pull request merged**
