### PR TITLE
Defect -13091737 Added check for disabling the rate even if the user is ...

### PR DESCRIPTION
**Pull request by CHenrie**
@jbest84 Please Review

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Validated by QA as fixed. Merging.

**Comment by jbest84** [comment]
@CHenrie Accept.

**Pull request merged**
