### PR TITLE
[13091801] Disable the ability to complete recurring activities as a qui...

### PR DESCRIPTION
**Pull request by jbest84**
...ck action. These types must be completed differently from the detail view (Complete Occurance or Complete Series).

@CHenrie Please review.

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by CHenrie** [comment]
@jbest84 Accepted

**Comment by gitCHenrie** [comment]
@jbest84 Accepted

**Comment by jbest84** [comment]
Validated by QA. Merging.

**Pull request merged**
