### PR TITLE
This commit fixes issue #83

### PR DESCRIPTION
**Pull request by jbest84**

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by csueiras** [comment]
I missed a comma, it has been added, suggest accepting the latest commit.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Assigned to DTS# 13091937

**Pull request merged**
