### PR TITLE
[13091658] Fixed speedsearch for activities, notes history, and tickets.

### PR DESCRIPTION
**Pull request by jbest84**
@CHenrie Please review

### CODE REVIEW

**Comment by jbest84** [comment]
You can view the fix in topic branch build 13

**Comment by CHenrie** [comment]
@jbest84  Accepted: Looks Good

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
Validated as fixed by QA in DTS.

**Pull request merged**
