### PR TITLE
defect 13092240 Adding support for configuration of file type to view as...

### PR DESCRIPTION
**Pull request by CHenrie**
... image

### CODE REVIEW

**Comment by CHenrie** [comment]
@jbest84  Please Review

**Comment by jbest84** [comment]
@CHenrie Application.js needs the properties you referenced so it can be configured properly.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
@CHenrie Accept

**Pull request merged**
