### PR TITLE
Topic attachement defects

### PR DESCRIPTION
**Pull request by CHenrie**
@jbest84  Please review

### CODE REVIEW

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by slxbuilder** [comment]
Merged build triggered.

**Comment by slxbuilder** [comment]
Merged build started.

**Comment by slxbuilder** [comment]
Merged build finished.

**Comment by jbest84** [comment]
@CHenrie Accept

**Pull request merged**
